// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type SubscribedUser struct {
	ID               uuid.UUID
	UserName         string
	TelegramID       int32
	TelegramChargeID string
	ProviderChargeID string
	SubscriptionDate sql.NullTime
}

type User struct {
	ID           uuid.UUID
	CreatedAt    sql.NullTime
	UserName     string
	TelegramID   int32
	Points       sql.NullInt32
	IsSubscribed sql.NullBool
}
